### ISSUE TITLE
poor segmentation results sometimes

### ISSUE THREAD

**Issue by dschneiderch** [Computational-Plant-Science/SMART#4]
Hi,
I tried this using the docker container at `computationalplantscience/spg` with my own data and had mixed results. 

without enhancing, 3 of 5 images were too dark but then it crashed...
```
root@3cd61e1633ed:/opt/dev# spg extract data/vis/test -o output/spg-output-noenhance -m -t data/vis_mask.tif
No timestamp in filename: A1-WT_VWC_Response3-20210208T072042-VIS0-0.png
No timestamp in filename: A1-WT_VWC_Response3-20210209T072040-VIS0-0.png
No timestamp in filename: A1-WT_VWC_Response3-20210210T092041-VIS0-0.png
No timestamp in filename: A1-WT_VWC_Response3-20210218T092041-VIS0-0.png
No timestamp in filename: A1-WT_VWC_Response3-20210219T092041-VIS0-0.png
Found 5 files with extensions jpg, png, jpeg, JPG, PNG, JPEG:
data/vis/test/A1-WT_VWC_Response3-20210208T072042-VIS0-0.png
data/vis/test/A1-WT_VWC_Response3-20210209T072040-VIS0-0.png
data/vis/test/A1-WT_VWC_Response3-20210210T092041-VIS0-0.png
data/vis/test/A1-WT_VWC_Response3-20210218T092041-VIS0-0.png
data/vis/test/A1-WT_VWC_Response3-20210219T092041-VIS0-0.png
Image A1-WT_VWC_Response3-20210208T072042-VIS0-0 is dark (normalized luminosity 0.08834961948850928 under threshold 0.1)
A1-WT_VWC_Response3-20210208T072042-VIS0-0 is too dark, skipping
Image A1-WT_VWC_Response3-20210209T072040-VIS0-0 is dark (normalized luminosity 0.07864052208646989 under threshold 0.1)
A1-WT_VWC_Response3-20210209T072040-VIS0-0 is too dark, skipping
Image A1-WT_VWC_Response3-20210210T092041-VIS0-0 is dark (normalized luminosity 0.08996759229738968 under threshold 0.1)
A1-WT_VWC_Response3-20210210T092041-VIS0-0 is too dark, skipping
Image A1-WT_VWC_Response3-20210218T092041-VIS0-0 is light enough (normalized luminosity 0.11492598600614728)
Writing to output/spg-output-noenhance/A1-WT_VWC_Response3-20210218T092041-VIS0-0.png
Image A1-WT_VWC_Response3-20210219T092041-VIS0-0 is light enough (normalized luminosity 0.11674658276253908)
Writing to output/spg-output-noenhance/A1-WT_VWC_Response3-20210219T092041-VIS0-0.png
No timestamp in filename: A1-WT_VWC_Response3-20210208T072042-VIS0-0.png
No timestamp in filename: A1-WT_VWC_Response3-20210209T072040-VIS0-0.png
No timestamp in filename: A1-WT_VWC_Response3-20210210T092041-VIS0-0.png
No timestamp in filename: A1-WT_VWC_Response3-20210218T092041-VIS0-0.png
No timestamp in filename: A1-WT_VWC_Response3-20210219T092041-VIS0-0.png
Checking for circle to crop in output/spg-output-noenhance/A1-WT_VWC_Response3-20210208T072042-VIS0-0.png
Traceback (most recent call last):
  File "/usr/local/bin/spg", line 11, in <module>
    load_entry_point('spg-topdown-traits', 'console_scripts', 'spg')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/spg-topdown-traits/core/cli.py", line 114, in extract
    cropped = circle_detect(input.input_file, template)
  File "/opt/spg-topdown-traits/core/luminous_detection.py", line 424, in circle_detect
    img_rgb = img_ori.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

then I enhanced the images, for example:

`spg enhance data/vis/test -o data/vis/test/enhanced -ft png`
`spg extract data/vis/test/enhanced -o output/spg-output -m -t data/vis_mask.tif`

an (enhanced) image
![image](https://user-images.githubusercontent.com/7461221/117732093-17624080-b1a4-11eb-9e7c-3961184ad267.png)

resulting mask
![image](https://user-images.githubusercontent.com/7461221/117732172-3c56b380-b1a4-11eb-90ae-14f372086613.png)

not a great result. 

But this one was good:
![image](https://user-images.githubusercontent.com/7461221/117732326-88095d00-b1a4-11eb-8999-4def838b636c.png)

![image](https://user-images.githubusercontent.com/7461221/117732304-8049b880-b1a4-11eb-8646-aac5f4c962f5.png)

here is my roi mask I created overlayed on one of the masks:
![my roi mask](https://user-images.githubusercontent.com/7461221/117731803-95721780-b1a3-11eb-834d-dde93abb9ee6.png)

does the mask not act as a filter?

I then tried with -l 0.05 to analyze the images without enhancing and it was also mixed:
![image](https://user-images.githubusercontent.com/7461221/117733883-2f878f00-b1a7-11eb-8eff-605ed4b9402e.png)

any suggestions to improve the segmentation?

**Comment by lsx1980** [comment]
Hi dschneiderch , our method was based on the color clustering methods, especially region-based clusters. Usually, we segment the pot first using a template marker and then our method was able to segment the plant object from the background. The illumination affects the image quality a lot, therefore plant color varies. We have provided some image enhance tools at the 'dev_code' folder. We would like to see your sample data with different illumination conditions if you can share some with us.
